### ISSUE TITLE
Have you taken down Nani.ninja for good?

### ISSUE THREAD

**Issue by dephunk** [destruc7i0n/nani#34]
And if so is there an alternative?

**Comment by destruc7i0n** [comment]
The site has been taken down by DMCA requests twice now that I have been sceptical of putting it up again since I do not want to lose accounts I use to host other personal applications.
Given that a suitable host were to make itself known, I would gladly put it back up again. I even recently paid for another year of domain registration.
I still do maintain it for personal use as well.

**Comment by destruc7i0n** [comment]
I brought it up once again. If it goes down this time, I will sadly have to stop hosting it publicly. Added a "login-wall" to hopefully prevent more DMCA takedowns.

**Comment by dephunk** [comment]
Is login working? Im getting "Your session with Crunchyroll has ended. Please login."

**Comment by destruc7i0n** [comment]
Just clear your cache and try again. Login has gotten more finicky these past few months ever since Crunchyroll updated their app to the new version.

**Comment by dephunk** [comment]
> Just clear your cache and try again. Login has gotten more finicky these past few months ever since Crunchyroll updated their app to the new version.

Yep fixed the issue. Thanks man! Love your work
