### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by DarkstaIkers** [destruc7i0n/nani#40]
Does API is down?

**Comment by destruc7i0n** [comment]
Yeah with the recent UI refresh the site has essentially stopped functioning

**Comment by DarkstaIkers** [comment]
> Yeah with the recent UI refresh the site has essentially stopped functioning

There's no way to get it back again?

**Comment by destruc7i0n** [comment]
Yeah they essentially deprecated the API this site was using and the new API would require the extension to bypass cors to be enabled all the time. I personally don't have many complaints with the new design so I don't really see a need to update this. This site was made because I hated the old design of Crunchyroll
